name: 'Debug Run'
trainer: binary
logging: false
tags:
  - debug

learning_rate: 0.0001
lr_factor: 0.1
lr_patience: 5

batch_size: 16
epochs: 5

patch_size: 32
stride: 32

datasets:
  image_path: 'D:/Pius/raw data/hoas_lh_tip_crop.tif'
  label_path: 'D:/Pius/Data/FingerSegmentation.tif'
  train:
    mask_path: 'D:/Pius/Data/Runs/Testing_Mask.tiff'
    cache_path: './cache/cache_debug'
  val:
     mask_path: 'D:/Pius/Data/Runs/validation_mask.tiff'
     cache_path: './cache/cache_debug_val'
cache: true
pad_mode: 'reflect'
pad_masked: 16
axis: 0
train_val_split_ration: 1
drop_until_equal: true

#loss_weights:
#  - 0.3
#  - 0.7

encoder:
  name: 'efficientnet-b1'
#  weights: 'imagenet'

transforms:
  general:
    - Clip:
       min_val: 90
       max_val: 195
  train:
    - Blur:
        blur_limit: 5

early_stopping:
  patience: 5
  min_delta: 0.0

seeds:
  data: 476
